-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgMAv67r+s1wzJKwnc
N/SYHWS/KXoT8r7PBQIfmpulsr2gCgYIKoZIzj0DAQehRANCAARwle4CozY+0bCM
BmOZgZotkr/8ccbOH7RadKIpuFg+GFmn6ZhzMF7SLP4x+vYEDPcfiqEOeE9Xb5KD
IXEkpV7V
-----END PRIVATE KEY-----