// gratitude — notice what has already been given.
module.exports = [
  ['Psalm 100:4', 'Enter into his gates with thanksgiving, and into his courts with praise. Give thanks to him, and bless his name.'],
  ['1 Thessalonians 5:16-18', 'Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus towards you.'],
  ['Psalm 107:1', 'Give thanks to the LORD, for he is good, for his loving kindness endures forever.'],
  ['James 1:17', 'Every good gift and every perfect gift is from above, coming down from the Father of lights.'],
  ['Psalm 103:2', "Praise the LORD, my soul, and don't forget all his benefits."],
  ['Colossians 3:15', 'And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful.'],
  ['Psalm 136:1', 'Give thanks to the LORD, for he is good, for his loving kindness endures forever.'],
  ['Psalm 34:8', 'Oh taste and see that the LORD is good. Blessed is the man who takes refuge in him.'],
  ['Philippians 4:8', 'Whatever things are true, whatever things are honourable, whatever things are lovely — think about these things.'],
  ['Ephesians 5:20', 'Giving thanks always concerning all things in the name of our Lord Jesus Christ to God, even the Father.'],
  ['Ruth 2:12', 'May the LORD repay your work, and a full reward be given to you from the LORD, under whose wings you have come to take refuge.'],
  ['Colossians 2:7', 'Rooted and built up in him and established in the faith, abounding in it in thanksgiving.'],
  ['2 Samuel 7:18', 'Who am I, Lord GOD, and what is my house, that you have brought me this far?'],
  ['Titus 3:5', 'Not by works of righteousness which we did ourselves, but according to his mercy, he saved us.'],
  ['1 Chronicles 16:34', 'Oh give thanks to the LORD, for he is good, for his loving kindness endures forever.'],
  ['Luke 17:15-16', 'One of them, when he saw that he was healed, turned back, glorifying God with a loud voice, and he fell on his face at Jesus’ feet, giving him thanks.'],
  ['Psalm 126:3', 'The LORD has done great things for us, and we are glad.'],
  ['2 Corinthians 9:15', 'Now thanks be to God for his unspeakable gift!'],
  ['Nehemiah 9:6', 'You are the LORD, even you alone. You have made heaven, the earth and all things that are on it. You preserve them all.'],
  ['Deuteronomy 8:10', 'You shall eat and be full, and you shall bless the LORD your God for the good land which he has given you.'],
  ['Psalm 65:11', 'You crown the year with your bounty. Your carts overflow with abundance.'],
  ['Psalm 104:14', 'He causes the grass to grow for the livestock, and plants for man to cultivate, that he may produce food out of the earth.'],
  ['1 Timothy 4:4', 'For every creature of God is good, and nothing is to be rejected if it is received with thanksgiving.'],
  ['Joel 2:26', 'You will have plenty to eat and be satisfied, and will praise the name of the LORD your God, who has dealt wondrously with you.'],
  ['Acts 14:17', 'He gave you rains from the sky and fruitful seasons, filling our hearts with food and gladness.'],
  ['2 Corinthians 4:15', 'For all things are for your sakes, that the grace, being multiplied through the many, may cause the thanksgiving to abound.'],
  ['Job 1:21', 'The LORD gave, and the LORD has taken away. Blessed be the LORD’s name.'],
  ['Haggai 2:9', 'In this place I will give peace, says the LORD of Armies.'],
  ['Revelation 7:12', 'Blessing, glory, wisdom, thanksgiving, honour, power, and might be to our God forever and ever!'],
  ['Philemon 1:7', 'For I had much joy and comfort in your love, because the hearts of the saints have been refreshed through you.'],
  ['1 Timothy 6:6', 'But godliness with contentment is great gain.'],
  ['Ecclesiastes 3:13', 'Also that every man should eat and drink, and enjoy good in all his labour — this is the gift of God.'],
  ['Psalm 16:6', 'The lines have fallen to me in pleasant places. Yes, I have a good inheritance.'],
  ['Psalm 8:3-4', 'When I consider your heavens, the work of your fingers, the moon and the stars, which you have ordained, what is man, that you think of him?'],
  ['Hebrews 12:28', 'Let’s have grace, through which we serve God acceptably, with reverence and awe.'],
  ['Psalm 23:5', 'You prepare a table before me. You anoint my head with oil. My cup runs over.'],
  ['Isaiah 12:4', 'Give thanks to the LORD! Call on his name! Declare his doings among the peoples!'],
  ['Psalm 147:7-8', 'Sing to the LORD with thanksgiving. He covers the sky with clouds, prepares rain for the earth, and makes grass grow on the mountains.'],
  ['1 Corinthians 15:57', 'But thanks be to God, who gives us the victory through our Lord Jesus Christ.'],
  ['1 Peter 1:3', 'Blessed be the God and Father of our Lord Jesus Christ, who according to his great mercy caused us to be born again to a living hope.'],
  ['Jonah 2:9', 'But I will sacrifice to you with the voice of thanksgiving. Salvation belongs to the LORD.'],
  ['Psalm 150:6', 'Let everything that has breath praise the LORD! Praise the LORD!'],
  ['Matthew 6:26', 'See the birds of the sky, that they don’t sow, neither do they reap. Your heavenly Father feeds them. Aren’t you of much more value than they?'],
  ['Psalm 34:1', 'I will bless the LORD at all times. His praise will always be in my mouth.'],
  ['Romans 8:32', 'He who didn’t spare his own Son, but delivered him up for us all, how would he not also with him freely give us all things?'],
  ['Psalm 145:16', 'You open your hand, and satisfy the desire of every living thing.'],
  ['1 Chronicles 29:14', 'For all things come from you, and we have given you of your own.'],
  ['Psalm 66:5', 'Come and see God’s deeds — awesome work on behalf of the children of men.'],
  ['Numbers 6:24-26', 'The LORD bless you and keep you. The LORD make his face to shine on you, and be gracious to you.'],
  ['Psalm 30:11-12', 'You have turned my mourning into dancing for me. To the end that my heart may sing praise to you, and not be silent.'],
  ['PRAYER:On the way home', 'For the road behind me and the people on it — thank you. Let me carry home what I was given, and not only what I noticed.'],
  ['PRAYER:Counting slowly', 'Before I ask for anything: three things you have already given me today. Let me name them, and mean them.'],
  ['PRAYER:For small mercies', 'For the ordinary and unremarkable things that held today together — I did not make any of them. Thank you.'],
];
