// intercession — carry someone else a while.
module.exports = [
  ['Philippians 4:6', 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.'],
  ['Galatians 6:2', 'Bear one another’s burdens, and so fulfil the law of Christ.'],
  ['James 5:16', 'Confess your sins to one another and pray for one another, that you may be healed. The insistent prayer of a righteous person is powerfully effective.'],
  ['1 Timothy 2:1', 'I exhort therefore, first of all, that petitions, prayers, intercessions, and givings of thanks be made for all people.'],
  ['Matthew 7:7', 'Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you.'],
  ['Romans 12:12', 'Rejoicing in hope; enduring in troubles; continuing steadfastly in prayer.'],
  ['Ephesians 6:18', 'With all prayer and requests, praying at all times in the Spirit, and being watchful with all perseverance and requests for all the saints.'],
  ['Colossians 4:2', 'Continue steadfastly in prayer, watching in it with thanksgiving.'],
  ['Luke 18:1', 'He also spoke a parable to them that they must always pray and not give up.'],
  ['1 John 5:14', 'This is the boldness which we have towards him, that if we ask anything according to his will, he listens to us.'],
  ['Romans 8:26', 'The Spirit also helps our weaknesses, for we don’t know how to pray as we ought.'],
  ['Hebrews 4:16', 'Let’s therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need.'],
  ['Matthew 18:20', 'For where two or three are gathered together in my name, there I am in the middle of them.'],
  ['John 15:12', 'This is my commandment, that you love one another, even as I have loved you.'],
  ['1 Peter 5:7', 'Casting all your worries on him, because he cares for you.'],
  ['Exodus 17:12', 'Aaron and Hur held up his hands, one on one side, and the other on the other side. His hands were steady until sunset.'],
  ['Job 42:10', 'The LORD restored Job’s prosperity when he prayed for his friends.'],
  ['Acts 12:5', 'Peter therefore was kept in the prison, but constant prayer was made by the assembly to God for him.'],
  ['2 Corinthians 1:11', 'You also helping together on our behalf by your supplication.'],
  ['Ephesians 3:14-15', 'For this cause, I bow my knees to the Father of our Lord Jesus Christ, from whom every family in heaven and on earth is named.'],
  ['Psalm 122:6', 'Pray for the peace of Jerusalem. Those who love you will prosper.'],
  ['Matthew 5:44', 'But I tell you, love your enemies, bless those who curse you, and pray for those who mistreat you.'],
  ['Luke 22:32', 'But I prayed for you, that your faith wouldn’t fail.'],
  ['Romans 15:1', 'Now we who are strong ought to bear the weaknesses of the weak, and not to please ourselves.'],
  ['Philippians 2:4', 'Each of you not just looking to his own things, but each of you also to the things of others.'],
  ['1 Samuel 12:23', 'Far be it from me that I should sin against the LORD in ceasing to pray for you.'],
  ['Isaiah 58:7', 'Isn’t it to share your bread with the hungry, and that you bring the poor who are cast out to your house?'],
  ['Matthew 25:40', 'Most certainly I tell you, because you did it to one of the least of these my brothers, you did it to me.'],
  ['Hebrews 13:3', 'Remember those who are in bonds, as bound with them, and those who are ill-treated, since you are also in the body.'],
  ['Galatians 6:10', 'So then, as we have opportunity, let’s do what is good towards all men, and especially towards those who are of the household of the faith.'],
  ['James 2:15-16', 'If a brother or sister is naked and in lack of daily food, and one of you tells them, "Go in peace," what good is it?'],
  ['Proverbs 31:8', 'Open your mouth for the mute, in the cause of all who are left desolate.'],
  ['1 John 3:18', 'My little children, let’s not love in word only, or with the tongue only, but in deed and truth.'],
  ['Romans 12:15', 'Rejoice with those who rejoice. Weep with those who weep.'],
  ['Colossians 1:9', 'We don’t cease praying and making requests for you, that you may be filled with the knowledge of his will.'],
  ['2 Thessalonians 1:11', 'To this end we also pray always for you, that our God may count you worthy of your calling.'],
  ['Psalm 20:1', 'May the LORD answer you in the day of trouble. May the name of the God of Jacob set you up on high.'],
  ['Luke 10:33-34', 'But a certain Samaritan, as he travelled, came where he was. When he saw him, he was moved with compassion.'],
  ['Genesis 18:32', 'He said, "Oh don’t let the Lord be angry, and I will speak just once more."'],
  ['Numbers 14:19', 'Please pardon the iniquity of this people according to the greatness of your loving kindness.'],
  ['Ezekiel 22:30', 'I sought for a man among them who would build up the wall and stand in the gap before me for the land.'],
  ['Daniel 9:18', 'For we do not present our petitions before you for our righteousness, but for your great mercies’ sake.'],
  ['John 17:20', 'Not for these only do I pray, but for those also who will believe in me through their word.'],
  ['Romans 8:34', 'It is Christ who died, yes rather, who was raised from the dead, who is at the right hand of God, who also makes intercession for us.'],
  ['Hebrews 7:25', 'He is also able to save to the uttermost those who draw near to God through him, seeing that he lives forever to make intercession for them.'],
  ['Matthew 9:36-38', 'When he saw the multitudes, he was moved with compassion for them. He said, "Pray therefore that the Lord of the harvest will send out labourers."'],
  ['1 Thessalonians 5:11', 'Therefore exhort one another, and build each other up, even as you also do.'],
  ['Psalm 72:12', 'For he will deliver the needy when he cries; the poor, who has no helper.'],
  ['Micah 6:8', 'What does the LORD require of you, but to act justly, to love mercy, and to walk humbly with your God?'],
  ['Isaiah 1:17', 'Learn to do well. Seek justice. Relieve the oppressed. Defend the fatherless. Plead for the widow.'],
  ['PRAYER:Carrying someone', 'I am walking this stretch for one person. Lord, you know the name. Let this ground be prayed over on their behalf.'],
  ['PRAYER:For whoever is next', 'For the next person I pass, whose day I know nothing about: mercy. Whatever they are carrying, help them carry it.'],
  ['PRAYER:The ones who are not here', 'For those too tired, too ill or too far away to walk today — I will do this stretch in their name.'],
];
