// lament — when the walk is heavy.
module.exports = [
  ['Psalm 34:18', 'The LORD is near to those who have a broken heart, and saves those who have a crushed spirit.'],
  ['Psalm 42:11', 'Why are you in despair, my soul? Why are you disturbed within me? Hope in God!'],
  ['Matthew 11:28', 'Come to me, all you who labour and are heavily burdened, and I will give you rest.'],
  ['Psalm 130:1-2', 'Out of the depths I have cried to you, LORD. Lord, hear my voice. Let your ears be attentive to the voice of my petitions.'],
  ['Psalm 23:4', 'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me.'],
  ['2 Corinthians 12:9', 'My grace is sufficient for you, for my power is made perfect in weakness.'],
  ['Psalm 56:8', 'You count my wanderings. You put my tears into your container. Aren’t they in your book?'],
  ['Psalm 13:1-2', 'How long, LORD? Will you forget me forever? How long will you hide your face from me?'],
  ['Psalm 22:1', 'My God, my God, why have you forsaken me? Why are you so far from helping me?'],
  ['Habakkuk 1:2', 'LORD, how long will I cry, and you will not hear? I cry out to you because of violence, and you will not save.'],
  ['Psalm 6:6', 'I am weary with my groaning. Every night I flood my bed. I drench my couch with my tears.'],
  ['Jeremiah 20:18', 'Why did I come out of the womb to see labour and sorrow, that my days should be consumed with shame?'],
  ['Psalm 88:1-2', 'LORD, the God of my salvation, I have cried day and night before you. Let my prayer enter into your presence.'],
  ['Lamentations 3:19-20', 'Remember my affliction and my misery, the wormwood and the bitterness. My soul still remembers them, and is bowed down within me.'],
  ['Job 3:26', 'I am not at ease, neither am I quiet, neither do I have rest; but trouble comes.'],
  ['Job 19:25', 'But as for me, I know that my Redeemer lives. In the end, he will stand upon the earth.'],
  ['Job 23:10', 'But he knows the way that I take. When he has tried me, I will come out like gold.'],
  ['Isaiah 53:3', 'He was despised and rejected by men, a man of suffering and acquainted with disease.'],
  ['Isaiah 43:2', 'When you pass through the waters, I will be with you, and through the rivers, they will not overflow you.'],
  ['Psalm 147:3', 'He heals the broken in heart, and binds up their wounds.'],
  ['Psalm 46:1', 'God is our refuge and strength, a very present help in trouble.'],
  ['Psalm 61:2', 'From the end of the earth, I will call to you when my heart is overwhelmed. Lead me to the rock that is higher than I.'],
  ['1 Peter 4:12', 'Beloved, don’t be astonished at the fiery trial which has come upon you to test you, as though a strange thing happened to you.'],
  ['John 11:35', 'Jesus wept.'],
  ['Matthew 26:38', 'My soul is exceedingly sorrowful, even to death. Stay here and watch with me.'],
  ['Luke 22:44', 'Being in agony he prayed more earnestly. His sweat became like great drops of blood falling down on the ground.'],
  ['Romans 8:18', 'For I consider that the sufferings of this present time are not worthy to be compared with the glory which will be revealed towards us.'],
  ['Romans 8:28', 'We know that all things work together for good for those who love God, for those who are called according to his purpose.'],
  ['2 Corinthians 4:8-9', 'We are pressed on every side, yet not crushed; perplexed, yet not to despair; pursued, yet not forsaken; struck down, yet not destroyed.'],
  ['2 Corinthians 1:3-4', 'The Father of mercies and God of all comfort, who comforts us in all our affliction.'],
  ['1 Peter 5:10', 'After you have suffered a little while, the God of all grace will himself perfect, establish, strengthen, and settle you.'],
  ['Revelation 21:4', 'He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain any more.'],
  ['Psalm 40:1-2', 'I waited patiently for the LORD. He turned to me, and heard my cry. He brought me up out of a horrible pit.'],
  ['Psalm 73:26', 'My flesh and my heart fails, but God is the strength of my heart and my portion forever.'],
  ['Ecclesiastes 7:3', 'Sorrow is better than laughter; for by the sadness of the face the heart is made good.'],
  ['Psalm 143:4', 'Therefore my spirit is overwhelmed within me. My heart within me is desolate.'],
  ['Jeremiah 29:11', 'For I know the thoughts that I think towards you, says the LORD, thoughts of peace, and not of evil, to give you hope and a future.'],
  ['Jeremiah 8:22', 'Is there no balm in Gilead? Is there no physician there?'],
  ['Habakkuk 3:17-18', 'Though the fig tree doesn’t flourish, nor fruit be in the vines, yet I will rejoice in the LORD. I will be joyful in the God of my salvation.'],
  ['Micah 7:7', 'But as for me, I will look to the LORD. I will wait for the God of my salvation. My God will hear me.'],
  ['Nahum 1:7', 'The LORD is good, a stronghold in the day of trouble; and he knows those who take refuge in him.'],
  ['Psalm 27:13-14', 'I am still confident of this: I will see the goodness of the LORD in the land of the living. Wait for the LORD.'],
  ['Ezekiel 36:26', 'I will give you a new heart, and I will put a new spirit within you. I will take away the stony heart out of your flesh.'],
  ['Isaiah 41:10', 'Don’t be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you.'],
  ['Isaiah 61:3', 'To give to them a garland for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness.'],
  ['Matthew 5:4', 'Blessed are those who mourn, for they shall be comforted.'],
  ['Psalm 116:3-4', 'The cords of death surrounded me, the pains of Sheol got a hold of me. Then I called on the LORD’s name.'],
  ['Ecclesiastes 3:4', 'A time to weep, and a time to laugh; a time to mourn, and a time to dance.'],
  ['Psalm 25:16-17', 'Turn to me, and have mercy on me, for I am desolate and afflicted. The troubles of my heart are enlarged.'],
  ['1 Kings 19:4', 'He requested for himself that he might die. He said, "It is enough. Now, O LORD, take away my life."'],
  ['Jude 1:24', 'Now to him who is able to keep them from stumbling, and to present you faultless before the presence of his glory in great joy.'],
  ['PRAYER:The Jesus Prayer', 'Lord Jesus Christ, Son of God, have mercy on me, a sinner.'],
  ['PRAYER:With no words left', 'I have nothing to say and I am saying it here, on this road, to you. Count that as the prayer.'],
  ['PRAYER:Kyrie', 'Lord, have mercy. Christ, have mercy. Lord, have mercy.'],
];
