// morningLight — the first walk of the day.
module.exports = [
  ['Psalm 5:3', 'LORD, in the morning you will hear my voice. In the morning I will lay my requests before you, and will watch expectantly.'],
  ['Lamentations 3:22-23', "It is because of the LORD's loving kindnesses that we are not consumed, because his compassion doesn't fail. They are new every morning."],
  ['Psalm 143:8', 'Cause me to hear your loving kindness in the morning, for I trust in you. Cause me to know the way in which I should walk.'],
  ['Mark 1:35', 'Early in the morning, while it was still dark, he rose up and went out, and departed into a deserted place, and prayed there.'],
  ['Psalm 118:24', 'This is the day that the LORD has made. We will rejoice and be glad in it.'],
  ['Isaiah 40:31', 'But those who wait for the LORD will renew their strength. They will mount up with wings like eagles. They will run, and not be weary.'],
  ['Psalm 30:5', 'Weeping may stay for the night, but joy comes in the morning.'],
  ['Psalm 90:14', 'Satisfy us in the morning with your loving kindness, that we may rejoice and be glad all our days.'],
  ['Psalm 59:16', 'But I will sing of your strength. Yes, I will sing aloud of your loving kindness in the morning.'],
  ['Joshua 3:5', 'Sanctify yourselves; for tomorrow the LORD will do wonders amongst you.'],
  ['Genesis 1:5', 'God called the light "day", and the darkness he called "night". There was evening and there was morning, the first day.'],
  ['Job 38:12', 'Have you commanded the morning in your days, and caused the dawn to know its place?'],
  ['Luke 1:78-79', 'Because of the tender mercy of our God, by which the dawn from on high will visit us, to shine on those who sit in darkness.'],
  ['Zephaniah 3:5', 'Morning by morning he brings his justice to light. He does not fail.'],
  ['Isaiah 50:4', 'He awakens morning by morning, he awakens my ear to hear as those who are taught.'],
  ['Psalm 63:1', "God, you are my God. I will seek you earnestly. My soul thirsts for you. My flesh longs for you, in a dry and weary land."],
  ['Psalm 88:13', 'But to you, LORD, I have cried. In the morning, my prayer comes before you.'],
  ['Psalm 19:1', 'The heavens declare the glory of God. The expanse shows his handiwork.'],
  ['Daniel 6:10', 'He knelt on his knees three times a day, and prayed and gave thanks before his God, as he did before.'],
  ['Hosea 6:3', 'His going out is as sure as the dawn. He will come to us like the rain, like the spring rain that waters the earth.'],
  ['Malachi 4:2', 'But to you who fear my name, the sun of righteousness will arise with healing in its wings.'],
  ['2 Peter 1:19', 'You do well that you heed it, as to a lamp shining in a dark place, until the day dawns and the morning star arises in your hearts.'],
  ['Proverbs 4:18', 'But the path of the righteous is like the dawning light that shines more and more until the perfect day.'],
  ['Psalm 92:1-2', 'It is a good thing to give thanks to the LORD, to proclaim your loving kindness in the morning, and your faithfulness every night.'],
  ['Exodus 16:7', 'In the morning you shall see the glory of the LORD.'],
  ['Psalm 108:2', 'Wake up, lute and harp! I will wake up the dawn.'],
  ['Deuteronomy 6:7', 'You shall talk of them when you sit in your house, and when you walk by the way, and when you lie down, and when you rise up.'],
  ['1 Samuel 3:10', 'The LORD came and stood, and called as at other times, "Samuel! Samuel!" Then Samuel said, "Speak; for your servant hears."'],
  ['Psalm 139:9-10', 'If I take the wings of the dawn, and settle in the uttermost parts of the sea, even there your hand will lead me.'],
  ['Isaiah 43:19', 'Behold, I will do a new thing. It springs out now. Don’t you know it? I will even make a way in the wilderness.'],
  ['Ecclesiastes 11:6', 'In the morning sow your seed, and in the evening don’t withhold your hand.'],
  ['Song of Songs 2:11-12', 'For behold, the winter is past. The rain is over and gone. The flowers appear on the earth. The time of the singing has come.'],
  ['Mark 16:2', 'Very early on the first day of the week, they came to the tomb when the sun had risen.'],
  ['John 21:4', 'But when day had already come, Jesus stood on the beach.'],
  ['Psalm 46:5', 'God is within her. She shall not be moved. God will help her at dawn.'],
  ['Job 11:17', 'Life will be clearer than the noonday. Though there is darkness, it will be as the morning.'],
  ['Amos 5:8', 'Seek him who made the Pleiades and Orion, and turns the shadow of death into the morning.'],
  ['Nehemiah 8:10', "Don't be grieved, for the joy of the LORD is your strength."],
  ['Psalm 143:10', 'Teach me to do your will, for you are my God. Your Spirit is good. Lead me in the land of uprightness.'],
  ['Isaiah 60:1', 'Arise, shine; for your light has come, and the glory of the LORD has risen on you.'],
  ['Matthew 6:34', "Therefore don't be anxious for tomorrow, for tomorrow will be anxious for itself. Each day's own evil is sufficient."],
  ['Zechariah 14:7', 'It will happen that at evening time there will be light.'],
  ['Lamentations 3:25', 'The LORD is good to those who wait for him, to the soul who seeks him.'],
  ['Psalm 27:1', 'The LORD is my light and my salvation. Whom shall I fear?'],
  ['Micah 7:8', 'When I sit in darkness, the LORD will be a light to me.'],
  ['Romans 13:12', 'The night is far gone, and the day is near. Let’s therefore throw off the deeds of darkness, and let’s put on the armour of light.'],
  ['2 Corinthians 5:17', 'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.'],
  ['Isaiah 33:2', 'LORD, be gracious to us. We have waited for you. Be our strength every morning, our salvation also in the time of trouble.'],
  ['Psalm 104:23', 'Man goes out to his work, to his labour until the evening.'],
  ['James 4:14', 'For what is your life? For you are a vapour that appears for a little time, and then vanishes away.'],
  ['PRAYER:Before the first mile', 'Lord, before the first mile: settle my breathing, slow my thoughts, and let me notice what you have already put in front of me.'],
  ['PRAYER:At the door', 'God of the morning, I am going out. Go with me, go before me, and be waiting when I come back.'],
  ['PRAYER:The first step', 'For this day I have not yet spent, and this road I have not yet walked: thank you. Keep me awake to both.'],
];
