// stillness — fewer words, slower feet.
module.exports = [
  ['Psalm 46:10', 'Be still, and know that I am God.'],
  ['1 Kings 19:12', 'After the earthquake a fire passed; but the LORD was not in the fire. After the fire, there was a still small voice.'],
  ['Psalm 62:1', 'My soul rests in God alone. My salvation is from him.'],
  ['Isaiah 30:15', 'You will be saved in returning and rest. Your strength will be in quietness and in confidence.'],
  ['Psalm 131:2', 'Surely I have stilled and quieted my soul, like a weaned child with his mother.'],
  ['Habakkuk 2:20', 'But the LORD is in his holy temple. Let all the earth be silent before him.'],
  ['Zechariah 2:13', 'Be silent, all flesh, before the LORD; for he has roused himself from his holy habitation!'],
  ['Zephaniah 3:17', 'He will rest in his love. He will rejoice over you with singing.'],
  ['Psalm 37:7', 'Rest in the LORD, and wait patiently for him.'],
  ['Psalm 62:5', 'My soul, wait in silence for God alone, for my expectation is from him.'],
  ['Lamentations 3:26', 'It is good that a man should hope and quietly wait for the salvation of the LORD.'],
  ['Ecclesiastes 5:2', 'Don’t be rash with your mouth, and don’t let your heart be hasty to utter anything before God. Therefore let your words be few.'],
  ['Proverbs 17:28', 'Even a fool, when he keeps silent, is counted wise.'],
  ['James 1:19', 'Let every man be swift to hear, slow to speak, and slow to anger.'],
  ['Matthew 6:6', 'But you, when you pray, enter into your inner room, and having shut your door, pray to your Father who is in secret.'],
  ['Matthew 6:7', 'In praying, don’t use vain repetitions, as the Gentiles do; for they think that they will be heard for their much speaking.'],
  ['Mark 6:31', 'Come away into a deserted place, and rest a while.'],
  ['Luke 5:16', 'But he withdrew himself into the desert and prayed.'],
  ['Luke 10:42', 'But one thing is needed. Mary has chosen the good part, which will not be taken away from her.'],
  ['Psalm 23:1-2', 'The LORD is my shepherd; I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters.'],
  ['Psalm 23:3', 'He restores my soul. He guides me in the paths of righteousness for his name’s sake.'],
  ['Exodus 14:14', 'The LORD will fight for you, and you shall be still.'],
  ['Exodus 33:14', 'My presence will go with you, and I will give you rest.'],
  ['Isaiah 26:3', 'You will keep whoever’s mind is steadfast in perfect peace, because he trusts in you.'],
  ['Isaiah 32:17', 'The work of righteousness will be peace, and the effect of righteousness, quietness and confidence forever.'],
  ['John 14:27', 'Peace I leave with you. My peace I give to you. Don’t let your heart be troubled, neither let it be fearful.'],
  ['Philippians 4:7', 'And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.'],
  ['Psalm 4:8', 'In peace I will both lie down and sleep, for you alone, LORD, make me live in safety.'],
  ['Psalm 4:4', 'Search your own heart on your bed, and be still.'],
  ['2 Kings 4:26', 'Please run now to meet her, and ask her, "Is it well with you?" She answered, "It is well."'],
  ['1 Thessalonians 4:11', 'Make it your ambition to lead a quiet life, and to do your own business, and to work with your own hands.'],
  ['Psalm 131:1', 'LORD, my heart isn’t arrogant, nor my eyes lofty; nor do I concern myself with great matters, or things too wonderful for me.'],
  ['Genesis 2:2', 'On the seventh day God finished his work which he had done; and he rested on the seventh day from all his work.'],
  ['Hebrews 4:9-10', 'There remains therefore a Sabbath rest for the people of God. For he who has entered into his rest has also rested from his works.'],
  ['Mark 4:39', 'He awoke and rebuked the wind, and said to the sea, "Peace! Be still!" The wind ceased and there was a great calm.'],
  ['Psalm 107:29-30', 'He makes the storm a calm, so that its waves are still. Then they are glad because it is calm.'],
  ['Job 37:14', 'Listen to this, Job. Stand still, and consider the wondrous works of God.'],
  ['1 Peter 3:4', 'But in the hidden person of the heart, in the incorruptible adornment of a gentle and quiet spirit, which is very precious in God’s sight.'],
  ['1 Corinthians 14:33', 'For God is not a God of confusion, but of peace.'],
  ['Colossians 3:2', 'Set your mind on the things that are above, not on the things that are on the earth.'],
  ['Isaiah 40:11', 'He will feed his flock like a shepherd. He will gather the lambs in his arm, and carry them in his bosom.'],
  ['Psalm 16:8', 'I have set the LORD always before me. Because he is at my right hand, I shall not be moved.'],
  ['Song of Songs 2:14', 'Let me see your face. Let me hear your voice; for your voice is sweet and your face is lovely.'],
  ['Obadiah 1:3', 'The pride of your heart has deceived you, you who dwell in the clefts of the rock, whose habitation is high.'],
  ['Numbers 9:19', 'When the cloud stayed on the tabernacle many days, then the children of Israel kept the LORD’s command, and didn’t travel.'],
  ['Psalm 27:4', 'One thing I have asked of the LORD, that I will seek after: that I may dwell in the house of the LORD all the days of my life.'],
  ['Ecclesiastes 4:6', 'Better is a handful, with quietness, than two handfuls with labour and chasing after wind.'],
  ['Isaiah 55:12', 'For you shall go out with joy, and be led out with peace. The mountains and the hills will break out before you into singing.'],
  ['2 Timothy 1:7', 'For God didn’t give us a spirit of fear, but of power, love, and self-control.'],
  ['Matthew 11:29', 'Take my yoke upon you and learn from me, for I am gentle and lowly in heart; and you will find rest for your souls.'],
  ['PRAYER:Fewer words', 'Enough words. I will walk the next stretch without asking you for anything, and let that be the prayer.'],
  ['PRAYER:Breathing', 'Breathing in: you are here. Breathing out: I am not in charge. Again, for as long as the road lasts.'],
  ['PRAYER:One word', 'One word for this mile, and no others: mercy. Or peace. Or here. Choose it, and keep returning to it.'],
];
