// scriptureWalk — the road, the way, the going.
module.exports = [
  ['Psalm 119:105', 'Your word is a lamp to my feet, and a light for my path.'],
  ['Luke 24:32', 'Weren’t our hearts burning within us while he spoke to us along the way, and while he opened the Scriptures to us?'],
  ['Proverbs 3:6', 'In all your ways acknowledge him, and he will make your paths straight.'],
  ['Psalm 16:11', 'You will show me the path of life. In your presence is fullness of joy.'],
  ['Deuteronomy 31:8', 'The LORD himself is who goes before you. He will be with you. He will not fail you, nor forsake you.'],
  ['Genesis 5:24', 'Enoch walked with God, and he was not found, for God took him.'],
  ['Isaiah 30:21', 'Your ears will hear a word behind you, saying, "This is the way. Walk in it."'],
  ['Micah 4:2', 'He will teach us of his ways, and we will walk in his paths.'],
  ['Jeremiah 6:16', 'Ask for the old paths, where the good way is, and walk in it; and you will find rest for your souls.'],
  ['Psalm 25:4', 'Show me your ways, LORD. Teach me your paths.'],
  ['Psalm 37:23', 'A man’s goings are established by the LORD. He delights in his way.'],
  ['Psalm 119:32', 'I run in the path of your commandments, for you have set my heart free.'],
  ['Psalm 119:35', 'Direct me in the path of your commandments, for I delight in them.'],
  ['Psalm 139:3', 'You search out my path and my lying down, and are acquainted with all my ways.'],
  ['Psalm 139:23-24', 'Search me, God, and know my heart. Try me, and know my thoughts. Lead me in the everlasting way.'],
  ['Proverbs 4:12', 'When you go, your steps will not be hampered. When you run, you will not stumble.'],
  ['Proverbs 4:26', 'Make the path of your feet level. Let all of your ways be established.'],
  ['Proverbs 16:9', 'A man’s heart plans his course, but the LORD directs his steps.'],
  ['Proverbs 20:24', 'A man’s steps are from the LORD; how then can man understand his way?'],
  ['Isaiah 2:3', 'Come, let’s go up to the mountain of the LORD, that he may teach us of his ways, and we may walk in his paths.'],
  ['Isaiah 35:8', 'A highway will be there, a road, and it will be called "The Holy Way".'],
  ['Isaiah 40:3', 'The voice of one who calls out, "Prepare the way of the LORD in the wilderness! Make a level highway in the desert for our God."'],
  ['Isaiah 42:16', 'I will bring the blind by a way that they don’t know. I will lead them in paths that they don’t know.'],
  ['John 14:6', 'Jesus said to him, "I am the way, the truth, and the life."'],
  ['John 8:12', 'I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life.'],
  ['John 10:27', 'My sheep hear my voice, and I know them, and they follow me.'],
  ['Matthew 4:19', 'He said to them, "Come after me, and I will make you fishers for men."'],
  ['Matthew 7:14', 'How narrow is the gate and the way is restricted that leads to life! There are few who find it.'],
  ['Mark 8:34', 'If anyone wants to come after me, let him deny himself, and take up his cross, and follow me.'],
  ['Luke 9:23', 'If anyone desires to come after me, let him deny himself, take up his cross, and follow me daily.'],
  ['Luke 24:15', 'While they talked and questioned together, Jesus himself came near, and went with them.'],
  ['Acts 9:2', 'That if he found any who were of the Way, whether men or women, he might bring them bound to Jerusalem.'],
  ['Acts 17:28', 'For in him we live, move, and have our being.'],
  ['Romans 12:2', 'Don’t be conformed to this world, but be transformed by the renewing of your mind.'],
  ['2 Corinthians 5:7', 'For we walk by faith, not by sight.'],
  ['Galatians 5:16', 'But I say, walk by the Spirit, and you won’t fulfil the lust of the flesh.'],
  ['Galatians 5:25', 'If we live by the Spirit, let’s also walk by the Spirit.'],
  ['Ephesians 5:2', 'Walk in love, even as Christ also loved you and gave himself up for us.'],
  ['Ephesians 5:15', 'Therefore watch carefully how you walk, not as unwise, but as wise.'],
  ['Colossians 2:6', 'As therefore you received Christ Jesus the Lord, walk in him.'],
  ['1 John 1:7', 'But if we walk in the light as he is in the light, we have fellowship with one another.'],
  ['1 John 2:6', 'He who says he remains in him ought himself also to walk just like he walked.'],
  ['Hebrews 12:1', 'Let’s lay aside every weight and the sin which so easily entangles us, and let’s run with perseverance the race that is set before us.'],
  ['Hebrews 11:8', 'By faith Abraham obeyed and went out to the place which he was to receive. He went out, not knowing where he went.'],
  ['Hebrews 13:14', 'For we don’t have here an enduring city, but we seek that which is to come.'],
  ['1 Peter 2:21', 'Because Christ also suffered for us, leaving you an example, that you should follow his steps.'],
  ['Psalm 84:7', 'They go from strength to strength.'],
  ['Psalm 121:8', 'The LORD will keep your going out and your coming in, from this time forward, and forever more.'],
  ['1 Corinthians 9:24', 'Don’t you know that those who run in a race all run, but one receives the prize? Run like that, that you may win.'],
  ['Revelation 21:24', 'The nations will walk in its light.'],
  ['PRAYER:Anima Christi', 'Soul of Christ, sanctify me. Body of Christ, save me. Within your wounds, hide me. Never let me be parted from you.'],
  ['PRAYER:The road ahead', 'I do not know what is round the next bend. You do. That will have to be enough, and it is.'],
  ['PRAYER:Step by step', 'Not the whole road — just the next step. Show me that one, and I will ask again after it.'],
];
