-- ===========================================================================
-- SEED — run once, by hand, by the maintainer. NOT a migration.
-- ===========================================================================
--
-- This file is deliberately not in `supabase/migrations/`. It is content, not
-- schema: re-running a migration must be safe on every project, whereas this
-- is a starting library that an admin is expected to edit, extend and prune
-- from the admin screens afterwards. Paste it into the Supabase SQL editor
-- after `20260727020000_scripture_prompts.sql` has been applied.
--
-- It is idempotent — a prompt with the same reference and translation is
-- skipped — so running it twice does not duplicate the library, and running it
-- again after an expansion adds only what is new.
--
-- SIZE, AND WHY IT IS THIS SIZE
-- ------------------------------
-- 319 prompts: 301 scripture and 18 prayers.
--
-- The library used to hold 47. At the default cadence a 5 km walk delivers
-- twelve of them, so two walks drawn independently from 47 collided 98% of the
-- time — see `docs/scripture_pool_audit.md`. Delivery history fixed the
-- *ordering* (unseen first, then least recently seen); this file fixes the
-- *arithmetic*. At this size a daily 5 km walker gets roughly a month before
-- any passage returns, and when one does it is the one longest unseen.
--
-- It is deliberately not larger. The licensed New Living Translation edition
-- of this same set is capped at 500 verses without written permission from
-- Tyndale, and a WEBBE library the NLT one cannot match would mean the two
-- editions delivering different walks. Grow both together, or neither.
--
-- LICENSING
-- ---------
-- Every scripture row below is the World English Bible, British Edition
-- (WEBBE): public domain, no licence fee, no attribution obligation. The
-- British edition is used rather than the base WEB because it renders the
-- divine name as "the LORD" rather than "Yahweh", which is the form Catholic
-- usage expects.
--
-- ⚠️ VERIFY THE TEXT BEFORE A PRODUCTION SEED. The passages were selected and
-- transcribed for this library rather than pulled programmatically from a
-- source file. Public domain means nobody is owed a fee, not that a
-- transcription error is acceptable in somebody's prayer. Diff this file
-- against https://ebible.org/webbe/ before seeding a parish, and treat any
-- mismatch as this file being wrong.
--
-- Rows with kind = 'prayer' carry no translation: they are either ancient
-- formulas long in the public domain (the Jesus Prayer, Anima Christi, the
-- Kyrie) or written for this app.
--
-- Nothing here is drawn from the NIV, ESV, NLT, NASB or CSB. Those are
-- copyrighted. Do not paste any of them into *this* file — it is the
-- public-domain set, and it is also what gets bundled into the binary.
--
-- Licensed New Living Translation rows have their own file:
-- `scripture_prompts_nlt_seed.sql.template`, which carries Tyndale's terms, the
-- 500-verse ceiling and the credit line. Both editions can live in this table
-- at once; `SCRIPTURE_TRANSLATION` decides which one a walk delivers. This set
-- is never replaced — it is the fallback, and the licence-free baseline the app
-- returns to if the licensed rows are ever pulled.
--
-- The same set ships as `assets/scripture/prompts.json`, which is the offline
-- floor when a device has never synced, and which stays WEBBE whatever the app
-- is configured to deliver. Both files are generated from one source; if you
-- edit one by hand, edit the other to match.

insert into public.scripture_prompts
  (reference, body, translation, kind, category, sort_order)
select v.reference, v.body, v.translation, v.kind, v.category, v.sort_order
from (values

  -- ----------------------------------------------------------- morning light --
  ('Psalm 5:3',
   'LORD, in the morning you will hear my voice. In the morning I will lay my requests before you, and will watch expectantly.',
   'WEBBE', 'scripture', 'morningLight', 1010),
  ('Lamentations 3:22-23',
   'It is because of the LORD''s loving kindnesses that we are not consumed, because his compassion doesn''t fail. They are new every morning.',
   'WEBBE', 'scripture', 'morningLight', 1020),
  ('Psalm 143:8',
   'Cause me to hear your loving kindness in the morning, for I trust in you. Cause me to know the way in which I should walk.',
   'WEBBE', 'scripture', 'morningLight', 1030),
  ('Mark 1:35',
   'Early in the morning, while it was still dark, he rose up and went out, and departed into a deserted place, and prayed there.',
   'WEBBE', 'scripture', 'morningLight', 1040),
  ('Psalm 118:24',
   'This is the day that the LORD has made. We will rejoice and be glad in it.',
   'WEBBE', 'scripture', 'morningLight', 1050),
  ('Isaiah 40:31',
   'But those who wait for the LORD will renew their strength. They will mount up with wings like eagles. They will run, and not be weary.',
   'WEBBE', 'scripture', 'morningLight', 1060),
  ('Psalm 30:5',
   'Weeping may stay for the night, but joy comes in the morning.',
   'WEBBE', 'scripture', 'morningLight', 1070),
  ('Psalm 90:14',
   'Satisfy us in the morning with your loving kindness, that we may rejoice and be glad all our days.',
   'WEBBE', 'scripture', 'morningLight', 1080),
  ('Psalm 59:16',
   'But I will sing of your strength. Yes, I will sing aloud of your loving kindness in the morning.',
   'WEBBE', 'scripture', 'morningLight', 1090),
  ('Joshua 3:5',
   'Sanctify yourselves; for tomorrow the LORD will do wonders amongst you.',
   'WEBBE', 'scripture', 'morningLight', 1100),
  ('Genesis 1:5',
   'God called the light "day", and the darkness he called "night". There was evening and there was morning, the first day.',
   'WEBBE', 'scripture', 'morningLight', 1110),
  ('Job 38:12',
   'Have you commanded the morning in your days, and caused the dawn to know its place?',
   'WEBBE', 'scripture', 'morningLight', 1120),
  ('Luke 1:78-79',
   'Because of the tender mercy of our God, by which the dawn from on high will visit us, to shine on those who sit in darkness.',
   'WEBBE', 'scripture', 'morningLight', 1130),
  ('Zephaniah 3:5',
   'Morning by morning he brings his justice to light. He does not fail.',
   'WEBBE', 'scripture', 'morningLight', 1140),
  ('Isaiah 50:4',
   'He awakens morning by morning, he awakens my ear to hear as those who are taught.',
   'WEBBE', 'scripture', 'morningLight', 1150),
  ('Psalm 63:1',
   'God, you are my God. I will seek you earnestly. My soul thirsts for you. My flesh longs for you, in a dry and weary land.',
   'WEBBE', 'scripture', 'morningLight', 1160),
  ('Psalm 88:13',
   'But to you, LORD, I have cried. In the morning, my prayer comes before you.',
   'WEBBE', 'scripture', 'morningLight', 1170),
  ('Psalm 19:1',
   'The heavens declare the glory of God. The expanse shows his handiwork.',
   'WEBBE', 'scripture', 'morningLight', 1180),
  ('Daniel 6:10',
   'He knelt on his knees three times a day, and prayed and gave thanks before his God, as he did before.',
   'WEBBE', 'scripture', 'morningLight', 1190),
  ('Hosea 6:3',
   'His going out is as sure as the dawn. He will come to us like the rain, like the spring rain that waters the earth.',
   'WEBBE', 'scripture', 'morningLight', 1200),
  ('Malachi 4:2',
   'But to you who fear my name, the sun of righteousness will arise with healing in its wings.',
   'WEBBE', 'scripture', 'morningLight', 1210),
  ('2 Peter 1:19',
   'You do well that you heed it, as to a lamp shining in a dark place, until the day dawns and the morning star arises in your hearts.',
   'WEBBE', 'scripture', 'morningLight', 1220),
  ('Proverbs 4:18',
   'But the path of the righteous is like the dawning light that shines more and more until the perfect day.',
   'WEBBE', 'scripture', 'morningLight', 1230),
  ('Psalm 92:1-2',
   'It is a good thing to give thanks to the LORD, to proclaim your loving kindness in the morning, and your faithfulness every night.',
   'WEBBE', 'scripture', 'morningLight', 1240),
  ('Exodus 16:7',
   'In the morning you shall see the glory of the LORD.',
   'WEBBE', 'scripture', 'morningLight', 1250),
  ('Psalm 108:2',
   'Wake up, lute and harp! I will wake up the dawn.',
   'WEBBE', 'scripture', 'morningLight', 1260),
  ('Deuteronomy 6:7',
   'You shall talk of them when you sit in your house, and when you walk by the way, and when you lie down, and when you rise up.',
   'WEBBE', 'scripture', 'morningLight', 1270),
  ('1 Samuel 3:10',
   'The LORD came and stood, and called as at other times, "Samuel! Samuel!" Then Samuel said, "Speak; for your servant hears."',
   'WEBBE', 'scripture', 'morningLight', 1280),
  ('Psalm 139:9-10',
   'If I take the wings of the dawn, and settle in the uttermost parts of the sea, even there your hand will lead me.',
   'WEBBE', 'scripture', 'morningLight', 1290),
  ('Isaiah 43:19',
   'Behold, I will do a new thing. It springs out now. Don’t you know it? I will even make a way in the wilderness.',
   'WEBBE', 'scripture', 'morningLight', 1300),
  ('Ecclesiastes 11:6',
   'In the morning sow your seed, and in the evening don’t withhold your hand.',
   'WEBBE', 'scripture', 'morningLight', 1310),
  ('Song of Songs 2:11-12',
   'For behold, the winter is past. The rain is over and gone. The flowers appear on the earth. The time of the singing has come.',
   'WEBBE', 'scripture', 'morningLight', 1320),
  ('Mark 16:2',
   'Very early on the first day of the week, they came to the tomb when the sun had risen.',
   'WEBBE', 'scripture', 'morningLight', 1330),
  ('John 21:4',
   'But when day had already come, Jesus stood on the beach.',
   'WEBBE', 'scripture', 'morningLight', 1340),
  ('Psalm 46:5',
   'God is within her. She shall not be moved. God will help her at dawn.',
   'WEBBE', 'scripture', 'morningLight', 1350),
  ('Job 11:17',
   'Life will be clearer than the noonday. Though there is darkness, it will be as the morning.',
   'WEBBE', 'scripture', 'morningLight', 1360),
  ('Amos 5:8',
   'Seek him who made the Pleiades and Orion, and turns the shadow of death into the morning.',
   'WEBBE', 'scripture', 'morningLight', 1370),
  ('Nehemiah 8:10',
   'Don''t be grieved, for the joy of the LORD is your strength.',
   'WEBBE', 'scripture', 'morningLight', 1380),
  ('Psalm 143:10',
   'Teach me to do your will, for you are my God. Your Spirit is good. Lead me in the land of uprightness.',
   'WEBBE', 'scripture', 'morningLight', 1390),
  ('Isaiah 60:1',
   'Arise, shine; for your light has come, and the glory of the LORD has risen on you.',
   'WEBBE', 'scripture', 'morningLight', 1400),
  ('Matthew 6:34',
   'Therefore don''t be anxious for tomorrow, for tomorrow will be anxious for itself. Each day''s own evil is sufficient.',
   'WEBBE', 'scripture', 'morningLight', 1410),
  ('Zechariah 14:7',
   'It will happen that at evening time there will be light.',
   'WEBBE', 'scripture', 'morningLight', 1420),
  ('Lamentations 3:25',
   'The LORD is good to those who wait for him, to the soul who seeks him.',
   'WEBBE', 'scripture', 'morningLight', 1430),
  ('Psalm 27:1',
   'The LORD is my light and my salvation. Whom shall I fear?',
   'WEBBE', 'scripture', 'morningLight', 1440),
  ('Micah 7:8',
   'When I sit in darkness, the LORD will be a light to me.',
   'WEBBE', 'scripture', 'morningLight', 1450),
  ('Romans 13:12',
   'The night is far gone, and the day is near. Let’s therefore throw off the deeds of darkness, and let’s put on the armour of light.',
   'WEBBE', 'scripture', 'morningLight', 1460),
  ('2 Corinthians 5:17',
   'Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.',
   'WEBBE', 'scripture', 'morningLight', 1470),
  ('Isaiah 33:2',
   'LORD, be gracious to us. We have waited for you. Be our strength every morning, our salvation also in the time of trouble.',
   'WEBBE', 'scripture', 'morningLight', 1480),
  ('Psalm 104:23',
   'Man goes out to his work, to his labour until the evening.',
   'WEBBE', 'scripture', 'morningLight', 1490),
  ('James 4:14',
   'For what is your life? For you are a vapour that appears for a little time, and then vanishes away.',
   'WEBBE', 'scripture', 'morningLight', 1500),
  ('Before the first mile',
   'Lord, before the first mile: settle my breathing, slow my thoughts, and let me notice what you have already put in front of me.',
   '', 'prayer', 'morningLight', 1510),
  ('At the door',
   'God of the morning, I am going out. Go with me, go before me, and be waiting when I come back.',
   '', 'prayer', 'morningLight', 1520),
  ('The first step',
   'For this day I have not yet spent, and this road I have not yet walked: thank you. Keep me awake to both.',
   '', 'prayer', 'morningLight', 1530),

  -- --------------------------------------------------------------- gratitude --
  ('Psalm 100:4',
   'Enter into his gates with thanksgiving, and into his courts with praise. Give thanks to him, and bless his name.',
   'WEBBE', 'scripture', 'gratitude', 2010),
  ('1 Thessalonians 5:16-18',
   'Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus towards you.',
   'WEBBE', 'scripture', 'gratitude', 2020),
  ('Psalm 107:1',
   'Give thanks to the LORD, for he is good, for his loving kindness endures forever.',
   'WEBBE', 'scripture', 'gratitude', 2030),
  ('James 1:17',
   'Every good gift and every perfect gift is from above, coming down from the Father of lights.',
   'WEBBE', 'scripture', 'gratitude', 2040),
  ('Psalm 103:2',
   'Praise the LORD, my soul, and don''t forget all his benefits.',
   'WEBBE', 'scripture', 'gratitude', 2050),
  ('Colossians 3:15',
   'And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful.',
   'WEBBE', 'scripture', 'gratitude', 2060),
  ('Psalm 136:1',
   'Give thanks to the LORD, for he is good, for his loving kindness endures forever.',
   'WEBBE', 'scripture', 'gratitude', 2070),
  ('Psalm 34:8',
   'Oh taste and see that the LORD is good. Blessed is the man who takes refuge in him.',
   'WEBBE', 'scripture', 'gratitude', 2080),
  ('Philippians 4:8',
   'Whatever things are true, whatever things are honourable, whatever things are lovely — think about these things.',
   'WEBBE', 'scripture', 'gratitude', 2090),
  ('Ephesians 5:20',
   'Giving thanks always concerning all things in the name of our Lord Jesus Christ to God, even the Father.',
   'WEBBE', 'scripture', 'gratitude', 2100),
  ('Ruth 2:12',
   'May the LORD repay your work, and a full reward be given to you from the LORD, under whose wings you have come to take refuge.',
   'WEBBE', 'scripture', 'gratitude', 2110),
  ('Colossians 2:7',
   'Rooted and built up in him and established in the faith, abounding in it in thanksgiving.',
   'WEBBE', 'scripture', 'gratitude', 2120),
  ('2 Samuel 7:18',
   'Who am I, Lord GOD, and what is my house, that you have brought me this far?',
   'WEBBE', 'scripture', 'gratitude', 2130),
  ('Titus 3:5',
   'Not by works of righteousness which we did ourselves, but according to his mercy, he saved us.',
   'WEBBE', 'scripture', 'gratitude', 2140),
  ('1 Chronicles 16:34',
   'Oh give thanks to the LORD, for he is good, for his loving kindness endures forever.',
   'WEBBE', 'scripture', 'gratitude', 2150),
  ('Luke 17:15-16',
   'One of them, when he saw that he was healed, turned back, glorifying God with a loud voice, and he fell on his face at Jesus’ feet, giving him thanks.',
   'WEBBE', 'scripture', 'gratitude', 2160),
  ('Psalm 126:3',
   'The LORD has done great things for us, and we are glad.',
   'WEBBE', 'scripture', 'gratitude', 2170),
  ('2 Corinthians 9:15',
   'Now thanks be to God for his unspeakable gift!',
   'WEBBE', 'scripture', 'gratitude', 2180),
  ('Nehemiah 9:6',
   'You are the LORD, even you alone. You have made heaven, the earth and all things that are on it. You preserve them all.',
   'WEBBE', 'scripture', 'gratitude', 2190),
  ('Deuteronomy 8:10',
   'You shall eat and be full, and you shall bless the LORD your God for the good land which he has given you.',
   'WEBBE', 'scripture', 'gratitude', 2200),
  ('Psalm 65:11',
   'You crown the year with your bounty. Your carts overflow with abundance.',
   'WEBBE', 'scripture', 'gratitude', 2210),
  ('Psalm 104:14',
   'He causes the grass to grow for the livestock, and plants for man to cultivate, that he may produce food out of the earth.',
   'WEBBE', 'scripture', 'gratitude', 2220),
  ('1 Timothy 4:4',
   'For every creature of God is good, and nothing is to be rejected if it is received with thanksgiving.',
   'WEBBE', 'scripture', 'gratitude', 2230),
  ('Joel 2:26',
   'You will have plenty to eat and be satisfied, and will praise the name of the LORD your God, who has dealt wondrously with you.',
   'WEBBE', 'scripture', 'gratitude', 2240),
  ('Acts 14:17',
   'He gave you rains from the sky and fruitful seasons, filling our hearts with food and gladness.',
   'WEBBE', 'scripture', 'gratitude', 2250),
  ('2 Corinthians 4:15',
   'For all things are for your sakes, that the grace, being multiplied through the many, may cause the thanksgiving to abound.',
   'WEBBE', 'scripture', 'gratitude', 2260),
  ('Job 1:21',
   'The LORD gave, and the LORD has taken away. Blessed be the LORD’s name.',
   'WEBBE', 'scripture', 'gratitude', 2270),
  ('Haggai 2:9',
   'In this place I will give peace, says the LORD of Armies.',
   'WEBBE', 'scripture', 'gratitude', 2280),
  ('Revelation 7:12',
   'Blessing, glory, wisdom, thanksgiving, honour, power, and might be to our God forever and ever!',
   'WEBBE', 'scripture', 'gratitude', 2290),
  ('Philemon 1:7',
   'For I had much joy and comfort in your love, because the hearts of the saints have been refreshed through you.',
   'WEBBE', 'scripture', 'gratitude', 2300),
  ('1 Timothy 6:6',
   'But godliness with contentment is great gain.',
   'WEBBE', 'scripture', 'gratitude', 2310),
  ('Ecclesiastes 3:13',
   'Also that every man should eat and drink, and enjoy good in all his labour — this is the gift of God.',
   'WEBBE', 'scripture', 'gratitude', 2320),
  ('Psalm 16:6',
   'The lines have fallen to me in pleasant places. Yes, I have a good inheritance.',
   'WEBBE', 'scripture', 'gratitude', 2330),
  ('Psalm 8:3-4',
   'When I consider your heavens, the work of your fingers, the moon and the stars, which you have ordained, what is man, that you think of him?',
   'WEBBE', 'scripture', 'gratitude', 2340),
  ('Hebrews 12:28',
   'Let’s have grace, through which we serve God acceptably, with reverence and awe.',
   'WEBBE', 'scripture', 'gratitude', 2350),
  ('Psalm 23:5',
   'You prepare a table before me. You anoint my head with oil. My cup runs over.',
   'WEBBE', 'scripture', 'gratitude', 2360),
  ('Isaiah 12:4',
   'Give thanks to the LORD! Call on his name! Declare his doings among the peoples!',
   'WEBBE', 'scripture', 'gratitude', 2370),
  ('Psalm 147:7-8',
   'Sing to the LORD with thanksgiving. He covers the sky with clouds, prepares rain for the earth, and makes grass grow on the mountains.',
   'WEBBE', 'scripture', 'gratitude', 2380),
  ('1 Corinthians 15:57',
   'But thanks be to God, who gives us the victory through our Lord Jesus Christ.',
   'WEBBE', 'scripture', 'gratitude', 2390),
  ('1 Peter 1:3',
   'Blessed be the God and Father of our Lord Jesus Christ, who according to his great mercy caused us to be born again to a living hope.',
   'WEBBE', 'scripture', 'gratitude', 2400),
  ('Jonah 2:9',
   'But I will sacrifice to you with the voice of thanksgiving. Salvation belongs to the LORD.',
   'WEBBE', 'scripture', 'gratitude', 2410),
  ('Psalm 150:6',
   'Let everything that has breath praise the LORD! Praise the LORD!',
   'WEBBE', 'scripture', 'gratitude', 2420),
  ('Matthew 6:26',
   'See the birds of the sky, that they don’t sow, neither do they reap. Your heavenly Father feeds them. Aren’t you of much more value than they?',
   'WEBBE', 'scripture', 'gratitude', 2430),
  ('Psalm 34:1',
   'I will bless the LORD at all times. His praise will always be in my mouth.',
   'WEBBE', 'scripture', 'gratitude', 2440),
  ('Romans 8:32',
   'He who didn’t spare his own Son, but delivered him up for us all, how would he not also with him freely give us all things?',
   'WEBBE', 'scripture', 'gratitude', 2450),
  ('Psalm 145:16',
   'You open your hand, and satisfy the desire of every living thing.',
   'WEBBE', 'scripture', 'gratitude', 2460),
  ('1 Chronicles 29:14',
   'For all things come from you, and we have given you of your own.',
   'WEBBE', 'scripture', 'gratitude', 2470),
  ('Psalm 66:5',
   'Come and see God’s deeds — awesome work on behalf of the children of men.',
   'WEBBE', 'scripture', 'gratitude', 2480),
  ('Numbers 6:24-26',
   'The LORD bless you and keep you. The LORD make his face to shine on you, and be gracious to you.',
   'WEBBE', 'scripture', 'gratitude', 2490),
  ('Psalm 30:11-12',
   'You have turned my mourning into dancing for me. To the end that my heart may sing praise to you, and not be silent.',
   'WEBBE', 'scripture', 'gratitude', 2500),
  ('On the way home',
   'For the road behind me and the people on it — thank you. Let me carry home what I was given, and not only what I noticed.',
   '', 'prayer', 'gratitude', 2510),
  ('Counting slowly',
   'Before I ask for anything: three things you have already given me today. Let me name them, and mean them.',
   '', 'prayer', 'gratitude', 2520),
  ('For small mercies',
   'For the ordinary and unremarkable things that held today together — I did not make any of them. Thank you.',
   '', 'prayer', 'gratitude', 2530),

  -- ------------------------------------------------------------ intercession --
  ('Philippians 4:6',
   'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God.',
   'WEBBE', 'scripture', 'intercession', 3010),
  ('Galatians 6:2',
   'Bear one another’s burdens, and so fulfil the law of Christ.',
   'WEBBE', 'scripture', 'intercession', 3020),
  ('James 5:16',
   'Confess your sins to one another and pray for one another, that you may be healed. The insistent prayer of a righteous person is powerfully effective.',
   'WEBBE', 'scripture', 'intercession', 3030),
  ('1 Timothy 2:1',
   'I exhort therefore, first of all, that petitions, prayers, intercessions, and givings of thanks be made for all people.',
   'WEBBE', 'scripture', 'intercession', 3040),
  ('Matthew 7:7',
   'Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you.',
   'WEBBE', 'scripture', 'intercession', 3050),
  ('Romans 12:12',
   'Rejoicing in hope; enduring in troubles; continuing steadfastly in prayer.',
   'WEBBE', 'scripture', 'intercession', 3060),
  ('Ephesians 6:18',
   'With all prayer and requests, praying at all times in the Spirit, and being watchful with all perseverance and requests for all the saints.',
   'WEBBE', 'scripture', 'intercession', 3070),
  ('Colossians 4:2',
   'Continue steadfastly in prayer, watching in it with thanksgiving.',
   'WEBBE', 'scripture', 'intercession', 3080),
  ('Luke 18:1',
   'He also spoke a parable to them that they must always pray and not give up.',
   'WEBBE', 'scripture', 'intercession', 3090),
  ('1 John 5:14',
   'This is the boldness which we have towards him, that if we ask anything according to his will, he listens to us.',
   'WEBBE', 'scripture', 'intercession', 3100),
  ('Romans 8:26',
   'The Spirit also helps our weaknesses, for we don’t know how to pray as we ought.',
   'WEBBE', 'scripture', 'intercession', 3110),
  ('Hebrews 4:16',
   'Let’s therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need.',
   'WEBBE', 'scripture', 'intercession', 3120),
  ('Matthew 18:20',
   'For where two or three are gathered together in my name, there I am in the middle of them.',
   'WEBBE', 'scripture', 'intercession', 3130),
  ('John 15:12',
   'This is my commandment, that you love one another, even as I have loved you.',
   'WEBBE', 'scripture', 'intercession', 3140),
  ('1 Peter 5:7',
   'Casting all your worries on him, because he cares for you.',
   'WEBBE', 'scripture', 'intercession', 3150),
  ('Exodus 17:12',
   'Aaron and Hur held up his hands, one on one side, and the other on the other side. His hands were steady until sunset.',
   'WEBBE', 'scripture', 'intercession', 3160),
  ('Job 42:10',
   'The LORD restored Job’s prosperity when he prayed for his friends.',
   'WEBBE', 'scripture', 'intercession', 3170),
  ('Acts 12:5',
   'Peter therefore was kept in the prison, but constant prayer was made by the assembly to God for him.',
   'WEBBE', 'scripture', 'intercession', 3180),
  ('2 Corinthians 1:11',
   'You also helping together on our behalf by your supplication.',
   'WEBBE', 'scripture', 'intercession', 3190),
  ('Ephesians 3:14-15',
   'For this cause, I bow my knees to the Father of our Lord Jesus Christ, from whom every family in heaven and on earth is named.',
   'WEBBE', 'scripture', 'intercession', 3200),
  ('Psalm 122:6',
   'Pray for the peace of Jerusalem. Those who love you will prosper.',
   'WEBBE', 'scripture', 'intercession', 3210),
  ('Matthew 5:44',
   'But I tell you, love your enemies, bless those who curse you, and pray for those who mistreat you.',
   'WEBBE', 'scripture', 'intercession', 3220),
  ('Luke 22:32',
   'But I prayed for you, that your faith wouldn’t fail.',
   'WEBBE', 'scripture', 'intercession', 3230),
  ('Romans 15:1',
   'Now we who are strong ought to bear the weaknesses of the weak, and not to please ourselves.',
   'WEBBE', 'scripture', 'intercession', 3240),
  ('Philippians 2:4',
   'Each of you not just looking to his own things, but each of you also to the things of others.',
   'WEBBE', 'scripture', 'intercession', 3250),
  ('1 Samuel 12:23',
   'Far be it from me that I should sin against the LORD in ceasing to pray for you.',
   'WEBBE', 'scripture', 'intercession', 3260),
  ('Isaiah 58:7',
   'Isn’t it to share your bread with the hungry, and that you bring the poor who are cast out to your house?',
   'WEBBE', 'scripture', 'intercession', 3270),
  ('Matthew 25:40',
   'Most certainly I tell you, because you did it to one of the least of these my brothers, you did it to me.',
   'WEBBE', 'scripture', 'intercession', 3280),
  ('Hebrews 13:3',
   'Remember those who are in bonds, as bound with them, and those who are ill-treated, since you are also in the body.',
   'WEBBE', 'scripture', 'intercession', 3290),
  ('Galatians 6:10',
   'So then, as we have opportunity, let’s do what is good towards all men, and especially towards those who are of the household of the faith.',
   'WEBBE', 'scripture', 'intercession', 3300),
  ('James 2:15-16',
   'If a brother or sister is naked and in lack of daily food, and one of you tells them, "Go in peace," what good is it?',
   'WEBBE', 'scripture', 'intercession', 3310),
  ('Proverbs 31:8',
   'Open your mouth for the mute, in the cause of all who are left desolate.',
   'WEBBE', 'scripture', 'intercession', 3320),
  ('1 John 3:18',
   'My little children, let’s not love in word only, or with the tongue only, but in deed and truth.',
   'WEBBE', 'scripture', 'intercession', 3330),
  ('Romans 12:15',
   'Rejoice with those who rejoice. Weep with those who weep.',
   'WEBBE', 'scripture', 'intercession', 3340),
  ('Colossians 1:9',
   'We don’t cease praying and making requests for you, that you may be filled with the knowledge of his will.',
   'WEBBE', 'scripture', 'intercession', 3350),
  ('2 Thessalonians 1:11',
   'To this end we also pray always for you, that our God may count you worthy of your calling.',
   'WEBBE', 'scripture', 'intercession', 3360),
  ('Psalm 20:1',
   'May the LORD answer you in the day of trouble. May the name of the God of Jacob set you up on high.',
   'WEBBE', 'scripture', 'intercession', 3370),
  ('Luke 10:33-34',
   'But a certain Samaritan, as he travelled, came where he was. When he saw him, he was moved with compassion.',
   'WEBBE', 'scripture', 'intercession', 3380),
  ('Genesis 18:32',
   'He said, "Oh don’t let the Lord be angry, and I will speak just once more."',
   'WEBBE', 'scripture', 'intercession', 3390),
  ('Numbers 14:19',
   'Please pardon the iniquity of this people according to the greatness of your loving kindness.',
   'WEBBE', 'scripture', 'intercession', 3400),
  ('Ezekiel 22:30',
   'I sought for a man among them who would build up the wall and stand in the gap before me for the land.',
   'WEBBE', 'scripture', 'intercession', 3410),
  ('Daniel 9:18',
   'For we do not present our petitions before you for our righteousness, but for your great mercies’ sake.',
   'WEBBE', 'scripture', 'intercession', 3420),
  ('John 17:20',
   'Not for these only do I pray, but for those also who will believe in me through their word.',
   'WEBBE', 'scripture', 'intercession', 3430),
  ('Romans 8:34',
   'It is Christ who died, yes rather, who was raised from the dead, who is at the right hand of God, who also makes intercession for us.',
   'WEBBE', 'scripture', 'intercession', 3440),
  ('Hebrews 7:25',
   'He is also able to save to the uttermost those who draw near to God through him, seeing that he lives forever to make intercession for them.',
   'WEBBE', 'scripture', 'intercession', 3450),
  ('Matthew 9:36-38',
   'When he saw the multitudes, he was moved with compassion for them. He said, "Pray therefore that the Lord of the harvest will send out labourers."',
   'WEBBE', 'scripture', 'intercession', 3460),
  ('1 Thessalonians 5:11',
   'Therefore exhort one another, and build each other up, even as you also do.',
   'WEBBE', 'scripture', 'intercession', 3470),
  ('Psalm 72:12',
   'For he will deliver the needy when he cries; the poor, who has no helper.',
   'WEBBE', 'scripture', 'intercession', 3480),
  ('Micah 6:8',
   'What does the LORD require of you, but to act justly, to love mercy, and to walk humbly with your God?',
   'WEBBE', 'scripture', 'intercession', 3490),
  ('Isaiah 1:17',
   'Learn to do well. Seek justice. Relieve the oppressed. Defend the fatherless. Plead for the widow.',
   'WEBBE', 'scripture', 'intercession', 3500),
  ('Carrying someone',
   'I am walking this stretch for one person. Lord, you know the name. Let this ground be prayed over on their behalf.',
   '', 'prayer', 'intercession', 3510),
  ('For whoever is next',
   'For the next person I pass, whose day I know nothing about: mercy. Whatever they are carrying, help them carry it.',
   '', 'prayer', 'intercession', 3520),
  ('The ones who are not here',
   'For those too tired, too ill or too far away to walk today — I will do this stretch in their name.',
   '', 'prayer', 'intercession', 3530),

  -- ------------------------------------------------------------------ lament --
  ('Psalm 34:18',
   'The LORD is near to those who have a broken heart, and saves those who have a crushed spirit.',
   'WEBBE', 'scripture', 'lament', 4010),
  ('Psalm 42:11',
   'Why are you in despair, my soul? Why are you disturbed within me? Hope in God!',
   'WEBBE', 'scripture', 'lament', 4020),
  ('Matthew 11:28',
   'Come to me, all you who labour and are heavily burdened, and I will give you rest.',
   'WEBBE', 'scripture', 'lament', 4030),
  ('Psalm 130:1-2',
   'Out of the depths I have cried to you, LORD. Lord, hear my voice. Let your ears be attentive to the voice of my petitions.',
   'WEBBE', 'scripture', 'lament', 4040),
  ('Psalm 23:4',
   'Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me.',
   'WEBBE', 'scripture', 'lament', 4050),
  ('2 Corinthians 12:9',
   'My grace is sufficient for you, for my power is made perfect in weakness.',
   'WEBBE', 'scripture', 'lament', 4060),
  ('Psalm 56:8',
   'You count my wanderings. You put my tears into your container. Aren’t they in your book?',
   'WEBBE', 'scripture', 'lament', 4070),
  ('Psalm 13:1-2',
   'How long, LORD? Will you forget me forever? How long will you hide your face from me?',
   'WEBBE', 'scripture', 'lament', 4080),
  ('Psalm 22:1',
   'My God, my God, why have you forsaken me? Why are you so far from helping me?',
   'WEBBE', 'scripture', 'lament', 4090),
  ('Habakkuk 1:2',
   'LORD, how long will I cry, and you will not hear? I cry out to you because of violence, and you will not save.',
   'WEBBE', 'scripture', 'lament', 4100),
  ('Psalm 6:6',
   'I am weary with my groaning. Every night I flood my bed. I drench my couch with my tears.',
   'WEBBE', 'scripture', 'lament', 4110),
  ('Jeremiah 20:18',
   'Why did I come out of the womb to see labour and sorrow, that my days should be consumed with shame?',
   'WEBBE', 'scripture', 'lament', 4120),
  ('Psalm 88:1-2',
   'LORD, the God of my salvation, I have cried day and night before you. Let my prayer enter into your presence.',
   'WEBBE', 'scripture', 'lament', 4130),
  ('Lamentations 3:19-20',
   'Remember my affliction and my misery, the wormwood and the bitterness. My soul still remembers them, and is bowed down within me.',
   'WEBBE', 'scripture', 'lament', 4140),
  ('Job 3:26',
   'I am not at ease, neither am I quiet, neither do I have rest; but trouble comes.',
   'WEBBE', 'scripture', 'lament', 4150),
  ('Job 19:25',
   'But as for me, I know that my Redeemer lives. In the end, he will stand upon the earth.',
   'WEBBE', 'scripture', 'lament', 4160),
  ('Job 23:10',
   'But he knows the way that I take. When he has tried me, I will come out like gold.',
   'WEBBE', 'scripture', 'lament', 4170),
  ('Isaiah 53:3',
   'He was despised and rejected by men, a man of suffering and acquainted with disease.',
   'WEBBE', 'scripture', 'lament', 4180),
  ('Isaiah 43:2',
   'When you pass through the waters, I will be with you, and through the rivers, they will not overflow you.',
   'WEBBE', 'scripture', 'lament', 4190),
  ('Psalm 147:3',
   'He heals the broken in heart, and binds up their wounds.',
   'WEBBE', 'scripture', 'lament', 4200),
  ('Psalm 46:1',
   'God is our refuge and strength, a very present help in trouble.',
   'WEBBE', 'scripture', 'lament', 4210),
  ('Psalm 61:2',
   'From the end of the earth, I will call to you when my heart is overwhelmed. Lead me to the rock that is higher than I.',
   'WEBBE', 'scripture', 'lament', 4220),
  ('1 Peter 4:12',
   'Beloved, don’t be astonished at the fiery trial which has come upon you to test you, as though a strange thing happened to you.',
   'WEBBE', 'scripture', 'lament', 4230),
  ('John 11:35',
   'Jesus wept.',
   'WEBBE', 'scripture', 'lament', 4240),
  ('Matthew 26:38',
   'My soul is exceedingly sorrowful, even to death. Stay here and watch with me.',
   'WEBBE', 'scripture', 'lament', 4250),
  ('Luke 22:44',
   'Being in agony he prayed more earnestly. His sweat became like great drops of blood falling down on the ground.',
   'WEBBE', 'scripture', 'lament', 4260),
  ('Romans 8:18',
   'For I consider that the sufferings of this present time are not worthy to be compared with the glory which will be revealed towards us.',
   'WEBBE', 'scripture', 'lament', 4270),
  ('Romans 8:28',
   'We know that all things work together for good for those who love God, for those who are called according to his purpose.',
   'WEBBE', 'scripture', 'lament', 4280),
  ('2 Corinthians 4:8-9',
   'We are pressed on every side, yet not crushed; perplexed, yet not to despair; pursued, yet not forsaken; struck down, yet not destroyed.',
   'WEBBE', 'scripture', 'lament', 4290),
  ('2 Corinthians 1:3-4',
   'The Father of mercies and God of all comfort, who comforts us in all our affliction.',
   'WEBBE', 'scripture', 'lament', 4300),
  ('1 Peter 5:10',
   'After you have suffered a little while, the God of all grace will himself perfect, establish, strengthen, and settle you.',
   'WEBBE', 'scripture', 'lament', 4310),
  ('Revelation 21:4',
   'He will wipe away every tear from their eyes. Death will be no more; neither will there be mourning, nor crying, nor pain any more.',
   'WEBBE', 'scripture', 'lament', 4320),
  ('Psalm 40:1-2',
   'I waited patiently for the LORD. He turned to me, and heard my cry. He brought me up out of a horrible pit.',
   'WEBBE', 'scripture', 'lament', 4330),
  ('Psalm 73:26',
   'My flesh and my heart fails, but God is the strength of my heart and my portion forever.',
   'WEBBE', 'scripture', 'lament', 4340),
  ('Ecclesiastes 7:3',
   'Sorrow is better than laughter; for by the sadness of the face the heart is made good.',
   'WEBBE', 'scripture', 'lament', 4350),
  ('Psalm 143:4',
   'Therefore my spirit is overwhelmed within me. My heart within me is desolate.',
   'WEBBE', 'scripture', 'lament', 4360),
  ('Jeremiah 29:11',
   'For I know the thoughts that I think towards you, says the LORD, thoughts of peace, and not of evil, to give you hope and a future.',
   'WEBBE', 'scripture', 'lament', 4370),
  ('Jeremiah 8:22',
   'Is there no balm in Gilead? Is there no physician there?',
   'WEBBE', 'scripture', 'lament', 4380),
  ('Habakkuk 3:17-18',
   'Though the fig tree doesn’t flourish, nor fruit be in the vines, yet I will rejoice in the LORD. I will be joyful in the God of my salvation.',
   'WEBBE', 'scripture', 'lament', 4390),
  ('Micah 7:7',
   'But as for me, I will look to the LORD. I will wait for the God of my salvation. My God will hear me.',
   'WEBBE', 'scripture', 'lament', 4400),
  ('Nahum 1:7',
   'The LORD is good, a stronghold in the day of trouble; and he knows those who take refuge in him.',
   'WEBBE', 'scripture', 'lament', 4410),
  ('Psalm 27:13-14',
   'I am still confident of this: I will see the goodness of the LORD in the land of the living. Wait for the LORD.',
   'WEBBE', 'scripture', 'lament', 4420),
  ('Ezekiel 36:26',
   'I will give you a new heart, and I will put a new spirit within you. I will take away the stony heart out of your flesh.',
   'WEBBE', 'scripture', 'lament', 4430),
  ('Isaiah 41:10',
   'Don’t be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you.',
   'WEBBE', 'scripture', 'lament', 4440),
  ('Isaiah 61:3',
   'To give to them a garland for ashes, the oil of joy for mourning, the garment of praise for the spirit of heaviness.',
   'WEBBE', 'scripture', 'lament', 4450),
  ('Matthew 5:4',
   'Blessed are those who mourn, for they shall be comforted.',
   'WEBBE', 'scripture', 'lament', 4460),
  ('Psalm 116:3-4',
   'The cords of death surrounded me, the pains of Sheol got a hold of me. Then I called on the LORD’s name.',
   'WEBBE', 'scripture', 'lament', 4470),
  ('Ecclesiastes 3:4',
   'A time to weep, and a time to laugh; a time to mourn, and a time to dance.',
   'WEBBE', 'scripture', 'lament', 4480),
  ('Psalm 25:16-17',
   'Turn to me, and have mercy on me, for I am desolate and afflicted. The troubles of my heart are enlarged.',
   'WEBBE', 'scripture', 'lament', 4490),
  ('1 Kings 19:4',
   'He requested for himself that he might die. He said, "It is enough. Now, O LORD, take away my life."',
   'WEBBE', 'scripture', 'lament', 4500),
  ('Jude 1:24',
   'Now to him who is able to keep them from stumbling, and to present you faultless before the presence of his glory in great joy.',
   'WEBBE', 'scripture', 'lament', 4510),
  ('The Jesus Prayer',
   'Lord Jesus Christ, Son of God, have mercy on me, a sinner.',
   '', 'prayer', 'lament', 4520),
  ('With no words left',
   'I have nothing to say and I am saying it here, on this road, to you. Count that as the prayer.',
   '', 'prayer', 'lament', 4530),
  ('Kyrie',
   'Lord, have mercy. Christ, have mercy. Lord, have mercy.',
   '', 'prayer', 'lament', 4540),

  -- --------------------------------------------------------------- stillness --
  ('Psalm 46:10',
   'Be still, and know that I am God.',
   'WEBBE', 'scripture', 'stillness', 5010),
  ('1 Kings 19:12',
   'After the earthquake a fire passed; but the LORD was not in the fire. After the fire, there was a still small voice.',
   'WEBBE', 'scripture', 'stillness', 5020),
  ('Psalm 62:1',
   'My soul rests in God alone. My salvation is from him.',
   'WEBBE', 'scripture', 'stillness', 5030),
  ('Isaiah 30:15',
   'You will be saved in returning and rest. Your strength will be in quietness and in confidence.',
   'WEBBE', 'scripture', 'stillness', 5040),
  ('Psalm 131:2',
   'Surely I have stilled and quieted my soul, like a weaned child with his mother.',
   'WEBBE', 'scripture', 'stillness', 5050),
  ('Habakkuk 2:20',
   'But the LORD is in his holy temple. Let all the earth be silent before him.',
   'WEBBE', 'scripture', 'stillness', 5060),
  ('Zechariah 2:13',
   'Be silent, all flesh, before the LORD; for he has roused himself from his holy habitation!',
   'WEBBE', 'scripture', 'stillness', 5070),
  ('Zephaniah 3:17',
   'He will rest in his love. He will rejoice over you with singing.',
   'WEBBE', 'scripture', 'stillness', 5080),
  ('Psalm 37:7',
   'Rest in the LORD, and wait patiently for him.',
   'WEBBE', 'scripture', 'stillness', 5090),
  ('Psalm 62:5',
   'My soul, wait in silence for God alone, for my expectation is from him.',
   'WEBBE', 'scripture', 'stillness', 5100),
  ('Lamentations 3:26',
   'It is good that a man should hope and quietly wait for the salvation of the LORD.',
   'WEBBE', 'scripture', 'stillness', 5110),
  ('Ecclesiastes 5:2',
   'Don’t be rash with your mouth, and don’t let your heart be hasty to utter anything before God. Therefore let your words be few.',
   'WEBBE', 'scripture', 'stillness', 5120),
  ('Proverbs 17:28',
   'Even a fool, when he keeps silent, is counted wise.',
   'WEBBE', 'scripture', 'stillness', 5130),
  ('James 1:19',
   'Let every man be swift to hear, slow to speak, and slow to anger.',
   'WEBBE', 'scripture', 'stillness', 5140),
  ('Matthew 6:6',
   'But you, when you pray, enter into your inner room, and having shut your door, pray to your Father who is in secret.',
   'WEBBE', 'scripture', 'stillness', 5150),
  ('Matthew 6:7',
   'In praying, don’t use vain repetitions, as the Gentiles do; for they think that they will be heard for their much speaking.',
   'WEBBE', 'scripture', 'stillness', 5160),
  ('Mark 6:31',
   'Come away into a deserted place, and rest a while.',
   'WEBBE', 'scripture', 'stillness', 5170),
  ('Luke 5:16',
   'But he withdrew himself into the desert and prayed.',
   'WEBBE', 'scripture', 'stillness', 5180),
  ('Luke 10:42',
   'But one thing is needed. Mary has chosen the good part, which will not be taken away from her.',
   'WEBBE', 'scripture', 'stillness', 5190),
  ('Psalm 23:1-2',
   'The LORD is my shepherd; I shall lack nothing. He makes me lie down in green pastures. He leads me beside still waters.',
   'WEBBE', 'scripture', 'stillness', 5200),
  ('Psalm 23:3',
   'He restores my soul. He guides me in the paths of righteousness for his name’s sake.',
   'WEBBE', 'scripture', 'stillness', 5210),
  ('Exodus 14:14',
   'The LORD will fight for you, and you shall be still.',
   'WEBBE', 'scripture', 'stillness', 5220),
  ('Exodus 33:14',
   'My presence will go with you, and I will give you rest.',
   'WEBBE', 'scripture', 'stillness', 5230),
  ('Isaiah 26:3',
   'You will keep whoever’s mind is steadfast in perfect peace, because he trusts in you.',
   'WEBBE', 'scripture', 'stillness', 5240),
  ('Isaiah 32:17',
   'The work of righteousness will be peace, and the effect of righteousness, quietness and confidence forever.',
   'WEBBE', 'scripture', 'stillness', 5250),
  ('John 14:27',
   'Peace I leave with you. My peace I give to you. Don’t let your heart be troubled, neither let it be fearful.',
   'WEBBE', 'scripture', 'stillness', 5260),
  ('Philippians 4:7',
   'And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.',
   'WEBBE', 'scripture', 'stillness', 5270),
  ('Psalm 4:8',
   'In peace I will both lie down and sleep, for you alone, LORD, make me live in safety.',
   'WEBBE', 'scripture', 'stillness', 5280),
  ('Psalm 4:4',
   'Search your own heart on your bed, and be still.',
   'WEBBE', 'scripture', 'stillness', 5290),
  ('2 Kings 4:26',
   'Please run now to meet her, and ask her, "Is it well with you?" She answered, "It is well."',
   'WEBBE', 'scripture', 'stillness', 5300),
  ('1 Thessalonians 4:11',
   'Make it your ambition to lead a quiet life, and to do your own business, and to work with your own hands.',
   'WEBBE', 'scripture', 'stillness', 5310),
  ('Psalm 131:1',
   'LORD, my heart isn’t arrogant, nor my eyes lofty; nor do I concern myself with great matters, or things too wonderful for me.',
   'WEBBE', 'scripture', 'stillness', 5320),
  ('Genesis 2:2',
   'On the seventh day God finished his work which he had done; and he rested on the seventh day from all his work.',
   'WEBBE', 'scripture', 'stillness', 5330),
  ('Hebrews 4:9-10',
   'There remains therefore a Sabbath rest for the people of God. For he who has entered into his rest has also rested from his works.',
   'WEBBE', 'scripture', 'stillness', 5340),
  ('Mark 4:39',
   'He awoke and rebuked the wind, and said to the sea, "Peace! Be still!" The wind ceased and there was a great calm.',
   'WEBBE', 'scripture', 'stillness', 5350),
  ('Psalm 107:29-30',
   'He makes the storm a calm, so that its waves are still. Then they are glad because it is calm.',
   'WEBBE', 'scripture', 'stillness', 5360),
  ('Job 37:14',
   'Listen to this, Job. Stand still, and consider the wondrous works of God.',
   'WEBBE', 'scripture', 'stillness', 5370),
  ('1 Peter 3:4',
   'But in the hidden person of the heart, in the incorruptible adornment of a gentle and quiet spirit, which is very precious in God’s sight.',
   'WEBBE', 'scripture', 'stillness', 5380),
  ('1 Corinthians 14:33',
   'For God is not a God of confusion, but of peace.',
   'WEBBE', 'scripture', 'stillness', 5390),
  ('Colossians 3:2',
   'Set your mind on the things that are above, not on the things that are on the earth.',
   'WEBBE', 'scripture', 'stillness', 5400),
  ('Isaiah 40:11',
   'He will feed his flock like a shepherd. He will gather the lambs in his arm, and carry them in his bosom.',
   'WEBBE', 'scripture', 'stillness', 5410),
  ('Psalm 16:8',
   'I have set the LORD always before me. Because he is at my right hand, I shall not be moved.',
   'WEBBE', 'scripture', 'stillness', 5420),
  ('Song of Songs 2:14',
   'Let me see your face. Let me hear your voice; for your voice is sweet and your face is lovely.',
   'WEBBE', 'scripture', 'stillness', 5430),
  ('Obadiah 1:3',
   'The pride of your heart has deceived you, you who dwell in the clefts of the rock, whose habitation is high.',
   'WEBBE', 'scripture', 'stillness', 5440),
  ('Numbers 9:19',
   'When the cloud stayed on the tabernacle many days, then the children of Israel kept the LORD’s command, and didn’t travel.',
   'WEBBE', 'scripture', 'stillness', 5450),
  ('Psalm 27:4',
   'One thing I have asked of the LORD, that I will seek after: that I may dwell in the house of the LORD all the days of my life.',
   'WEBBE', 'scripture', 'stillness', 5460),
  ('Ecclesiastes 4:6',
   'Better is a handful, with quietness, than two handfuls with labour and chasing after wind.',
   'WEBBE', 'scripture', 'stillness', 5470),
  ('Isaiah 55:12',
   'For you shall go out with joy, and be led out with peace. The mountains and the hills will break out before you into singing.',
   'WEBBE', 'scripture', 'stillness', 5480),
  ('2 Timothy 1:7',
   'For God didn’t give us a spirit of fear, but of power, love, and self-control.',
   'WEBBE', 'scripture', 'stillness', 5490),
  ('Matthew 11:29',
   'Take my yoke upon you and learn from me, for I am gentle and lowly in heart; and you will find rest for your souls.',
   'WEBBE', 'scripture', 'stillness', 5500),
  ('Fewer words',
   'Enough words. I will walk the next stretch without asking you for anything, and let that be the prayer.',
   '', 'prayer', 'stillness', 5510),
  ('Breathing',
   'Breathing in: you are here. Breathing out: I am not in charge. Again, for as long as the road lasts.',
   '', 'prayer', 'stillness', 5520),
  ('One word',
   'One word for this mile, and no others: mercy. Or peace. Or here. Choose it, and keep returning to it.',
   '', 'prayer', 'stillness', 5530),

  -- ---------------------------------------------------------- scripture walk --
  ('Psalm 119:105',
   'Your word is a lamp to my feet, and a light for my path.',
   'WEBBE', 'scripture', 'scriptureWalk', 6010),
  ('Luke 24:32',
   'Weren’t our hearts burning within us while he spoke to us along the way, and while he opened the Scriptures to us?',
   'WEBBE', 'scripture', 'scriptureWalk', 6020),
  ('Proverbs 3:6',
   'In all your ways acknowledge him, and he will make your paths straight.',
   'WEBBE', 'scripture', 'scriptureWalk', 6030),
  ('Psalm 16:11',
   'You will show me the path of life. In your presence is fullness of joy.',
   'WEBBE', 'scripture', 'scriptureWalk', 6040),
  ('Deuteronomy 31:8',
   'The LORD himself is who goes before you. He will be with you. He will not fail you, nor forsake you.',
   'WEBBE', 'scripture', 'scriptureWalk', 6050),
  ('Genesis 5:24',
   'Enoch walked with God, and he was not found, for God took him.',
   'WEBBE', 'scripture', 'scriptureWalk', 6060),
  ('Isaiah 30:21',
   'Your ears will hear a word behind you, saying, "This is the way. Walk in it."',
   'WEBBE', 'scripture', 'scriptureWalk', 6070),
  ('Micah 4:2',
   'He will teach us of his ways, and we will walk in his paths.',
   'WEBBE', 'scripture', 'scriptureWalk', 6080),
  ('Jeremiah 6:16',
   'Ask for the old paths, where the good way is, and walk in it; and you will find rest for your souls.',
   'WEBBE', 'scripture', 'scriptureWalk', 6090),
  ('Psalm 25:4',
   'Show me your ways, LORD. Teach me your paths.',
   'WEBBE', 'scripture', 'scriptureWalk', 6100),
  ('Psalm 37:23',
   'A man’s goings are established by the LORD. He delights in his way.',
   'WEBBE', 'scripture', 'scriptureWalk', 6110),
  ('Psalm 119:32',
   'I run in the path of your commandments, for you have set my heart free.',
   'WEBBE', 'scripture', 'scriptureWalk', 6120),
  ('Psalm 119:35',
   'Direct me in the path of your commandments, for I delight in them.',
   'WEBBE', 'scripture', 'scriptureWalk', 6130),
  ('Psalm 139:3',
   'You search out my path and my lying down, and are acquainted with all my ways.',
   'WEBBE', 'scripture', 'scriptureWalk', 6140),
  ('Psalm 139:23-24',
   'Search me, God, and know my heart. Try me, and know my thoughts. Lead me in the everlasting way.',
   'WEBBE', 'scripture', 'scriptureWalk', 6150),
  ('Proverbs 4:12',
   'When you go, your steps will not be hampered. When you run, you will not stumble.',
   'WEBBE', 'scripture', 'scriptureWalk', 6160),
  ('Proverbs 4:26',
   'Make the path of your feet level. Let all of your ways be established.',
   'WEBBE', 'scripture', 'scriptureWalk', 6170),
  ('Proverbs 16:9',
   'A man’s heart plans his course, but the LORD directs his steps.',
   'WEBBE', 'scripture', 'scriptureWalk', 6180),
  ('Proverbs 20:24',
   'A man’s steps are from the LORD; how then can man understand his way?',
   'WEBBE', 'scripture', 'scriptureWalk', 6190),
  ('Isaiah 2:3',
   'Come, let’s go up to the mountain of the LORD, that he may teach us of his ways, and we may walk in his paths.',
   'WEBBE', 'scripture', 'scriptureWalk', 6200),
  ('Isaiah 35:8',
   'A highway will be there, a road, and it will be called "The Holy Way".',
   'WEBBE', 'scripture', 'scriptureWalk', 6210),
  ('Isaiah 40:3',
   'The voice of one who calls out, "Prepare the way of the LORD in the wilderness! Make a level highway in the desert for our God."',
   'WEBBE', 'scripture', 'scriptureWalk', 6220),
  ('Isaiah 42:16',
   'I will bring the blind by a way that they don’t know. I will lead them in paths that they don’t know.',
   'WEBBE', 'scripture', 'scriptureWalk', 6230),
  ('John 14:6',
   'Jesus said to him, "I am the way, the truth, and the life."',
   'WEBBE', 'scripture', 'scriptureWalk', 6240),
  ('John 8:12',
   'I am the light of the world. He who follows me will not walk in the darkness, but will have the light of life.',
   'WEBBE', 'scripture', 'scriptureWalk', 6250),
  ('John 10:27',
   'My sheep hear my voice, and I know them, and they follow me.',
   'WEBBE', 'scripture', 'scriptureWalk', 6260),
  ('Matthew 4:19',
   'He said to them, "Come after me, and I will make you fishers for men."',
   'WEBBE', 'scripture', 'scriptureWalk', 6270),
  ('Matthew 7:14',
   'How narrow is the gate and the way is restricted that leads to life! There are few who find it.',
   'WEBBE', 'scripture', 'scriptureWalk', 6280),
  ('Mark 8:34',
   'If anyone wants to come after me, let him deny himself, and take up his cross, and follow me.',
   'WEBBE', 'scripture', 'scriptureWalk', 6290),
  ('Luke 9:23',
   'If anyone desires to come after me, let him deny himself, take up his cross, and follow me daily.',
   'WEBBE', 'scripture', 'scriptureWalk', 6300),
  ('Luke 24:15',
   'While they talked and questioned together, Jesus himself came near, and went with them.',
   'WEBBE', 'scripture', 'scriptureWalk', 6310),
  ('Acts 9:2',
   'That if he found any who were of the Way, whether men or women, he might bring them bound to Jerusalem.',
   'WEBBE', 'scripture', 'scriptureWalk', 6320),
  ('Acts 17:28',
   'For in him we live, move, and have our being.',
   'WEBBE', 'scripture', 'scriptureWalk', 6330),
  ('Romans 12:2',
   'Don’t be conformed to this world, but be transformed by the renewing of your mind.',
   'WEBBE', 'scripture', 'scriptureWalk', 6340),
  ('2 Corinthians 5:7',
   'For we walk by faith, not by sight.',
   'WEBBE', 'scripture', 'scriptureWalk', 6350),
  ('Galatians 5:16',
   'But I say, walk by the Spirit, and you won’t fulfil the lust of the flesh.',
   'WEBBE', 'scripture', 'scriptureWalk', 6360),
  ('Galatians 5:25',
   'If we live by the Spirit, let’s also walk by the Spirit.',
   'WEBBE', 'scripture', 'scriptureWalk', 6370),
  ('Ephesians 5:2',
   'Walk in love, even as Christ also loved you and gave himself up for us.',
   'WEBBE', 'scripture', 'scriptureWalk', 6380),
  ('Ephesians 5:15',
   'Therefore watch carefully how you walk, not as unwise, but as wise.',
   'WEBBE', 'scripture', 'scriptureWalk', 6390),
  ('Colossians 2:6',
   'As therefore you received Christ Jesus the Lord, walk in him.',
   'WEBBE', 'scripture', 'scriptureWalk', 6400),
  ('1 John 1:7',
   'But if we walk in the light as he is in the light, we have fellowship with one another.',
   'WEBBE', 'scripture', 'scriptureWalk', 6410),
  ('1 John 2:6',
   'He who says he remains in him ought himself also to walk just like he walked.',
   'WEBBE', 'scripture', 'scriptureWalk', 6420),
  ('Hebrews 12:1',
   'Let’s lay aside every weight and the sin which so easily entangles us, and let’s run with perseverance the race that is set before us.',
   'WEBBE', 'scripture', 'scriptureWalk', 6430),
  ('Hebrews 11:8',
   'By faith Abraham obeyed and went out to the place which he was to receive. He went out, not knowing where he went.',
   'WEBBE', 'scripture', 'scriptureWalk', 6440),
  ('Hebrews 13:14',
   'For we don’t have here an enduring city, but we seek that which is to come.',
   'WEBBE', 'scripture', 'scriptureWalk', 6450),
  ('1 Peter 2:21',
   'Because Christ also suffered for us, leaving you an example, that you should follow his steps.',
   'WEBBE', 'scripture', 'scriptureWalk', 6460),
  ('Psalm 84:7',
   'They go from strength to strength.',
   'WEBBE', 'scripture', 'scriptureWalk', 6470),
  ('Psalm 121:8',
   'The LORD will keep your going out and your coming in, from this time forward, and forever more.',
   'WEBBE', 'scripture', 'scriptureWalk', 6480),
  ('1 Corinthians 9:24',
   'Don’t you know that those who run in a race all run, but one receives the prize? Run like that, that you may win.',
   'WEBBE', 'scripture', 'scriptureWalk', 6490),
  ('Revelation 21:24',
   'The nations will walk in its light.',
   'WEBBE', 'scripture', 'scriptureWalk', 6500),
  ('Anima Christi',
   'Soul of Christ, sanctify me. Body of Christ, save me. Within your wounds, hide me. Never let me be parted from you.',
   '', 'prayer', 'scriptureWalk', 6510),
  ('The road ahead',
   'I do not know what is round the next bend. You do. That will have to be enough, and it is.',
   '', 'prayer', 'scriptureWalk', 6520),
  ('Step by step',
   'Not the whole road — just the next step. Show me that one, and I will ask again after it.',
   '', 'prayer', 'scriptureWalk', 6530)
) as v(reference, body, translation, kind, category, sort_order)
-- Idempotent on reference + edition, so a second run after an expansion adds
-- the new passages without duplicating the old ones.
where not exists (
  select 1
  from public.scripture_prompts p
  where p.reference = v.reference and p.translation = v.translation
);

-- What landed, by theme — run after seeding to confirm the spread.
--
--   select category, kind, count(*)
--     from public.scripture_prompts
--    where translation in ('WEBBE', '')
--    group by category, kind
--    order by category, kind;
